# Eureka Client 端配置
eureka:
  instance:
    hostname: localhost
    #   将自己 ip 注册到 Eureka Server
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: "http://username:password@${eureka.instance.hostname}:9001/eureka/,\
                    http://username:password@${eureka.instance.hostname}:9002/eureka/"

spring:
  application:
    name: eureka-client-consumer
server:
  port: 9021
